version: '3'
services:
  app:
    hostname: jellyfin
    image: devplayer0/jellyfin
    build: .
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./media:/media
    restart: on-failure